### ISSUE TITLE
Washington Post gives Access denied

### ISSUE THREAD

**Issue by SanderGit** [troysjanda/Paywall-Bypass#1]
The Washington Post gives an Access Denied for me (in the EU) with this add-on.

You don't have permission to access "http://www.washingtonpost.com/gdpr-consent/?" on this server.

When the add-on is disabled, the message does not occur.

**Comment by troysjanda** [comment]
Unable to reproduce with FF, and all addons disabled except Paywall-Bypass 1.0.13. If using ad blocker such as Ublock please purge and update filters

I did check with both Ubo/Nano Defender enabled and did not get that responce.

**Comment by SanderGit** [comment]
Likely related to a cookie warning.
